[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.alacritty]
input_path = '/home/vankata/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.zellij]
input_path = '/home/vankata/.config/matugen/templates/zellij.kdl'
output_path = '/home/vankata/.config/zellij/config.kdl'

[templates.rofi]
input_path = '/home/vankata/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/themes/colors.rasi'

[templates.gtk3]
input_path = '/home/vankata/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '/home/vankata/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.waybar]
input_path = '/home/vankata/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.starship]
input_path = '/home/vankata/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.zed]
input_path = '/home/vankata/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen.json'
