monitor = DP-3, 1920x1080@144, 0x0, 1
monitor = HDMI-A-4, 1680x1050@60, 1920x0, 1, transform, 1

env = HYPRCURSOR_THEME,Bibata-Original-Classic
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2

    resize_on_border = true

    col.active_border = rgba(6c13b6ff) rgba(020647ff) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

input {
    kb_layout = us, bg
    kb_variant =, bas_phonetic
    kb_options = grp:win_space_toggle

    follow_mouse = 1

    touchpad {
        natural_scroll = true
        scroll_factor = 0.2
    }

    sensitivity = 0
}

cursor {
    no_hardware_cursors = true
}

decoration {
    rounding = 5

    blur {
        size = 5
        passes = 5
        new_optimizations = true

    }

    active_opacity = 0.9
    inactive_opacity = 0.9

    layerrule = blur,waybar
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

$mainMod = SUPER

binds {
    movefocus_cycles_fullscreen = 1
}

# Apps
bind = $mainMod, Return, exec, alacritty
bind = $mainMod, R, exec, rofi -show drun

# Window management
bind = $mainMod, Q, killactive
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0
bind = $mainMod, A, layoutmsg, swapwithmaster master

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Focus (vim-style)
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# Resize
binde = $mainMod CTRL, H, resizeactive, -20 0
binde = $mainMod CTRL, L, resizeactive, 20 0
binde = $mainMod CTRL, K, resizeactive, 0 -20
binde = $mainMod CTRL, J, resizeactive, 0 20

# Utilities
bind = $mainMod, S, exec, grimshot copy area
bind = $mainMod, Escape, exec, hyprlock

# Volume
bindel =, XF86AudioRaiseVolume, exec, pamixer -i 5
bindel =, XF86AudioLowerVolume, exec, pamixer -d 5

# Playback
bind = $mainMod SHIFT, left, exec, playerctl previous
bind = $mainMod SHIFT, right, exec, playerctl next
bind = $mainMod SHIFT, P, exec, playerctl play-pause

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Scroll workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Autostart
exec-once = waybar
#exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waypaper --restore
